export default {
  background: require('../asset/images/background.png'),
  icongoBack: require('../asset/images/icongoBack.png'),
  backgroundend: require('../asset/images/backgroundend.png'),
  logo: require('../asset/images/logo.png'),
  font: require('../asset/images/font.png'),
  fly: require('../asset/images/fly.png'),
  one: require('../asset/images/1.jpg'),
  two: require('../asset/images/2.jpg'),
  three: require('../asset/images/3.jpg'),
  four: require('../asset/images/4.jpg'),
  five: require('../asset/images/5.png'),
  six: require('../asset/images/6.png'),
  seven: require('../asset/images/7.jpg'),
  eight: require('../asset/images/8.jpg'),
};
